spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543
    driverClassName: com.mysql.jdbc.Driver
    username: postgres.oxpaomatnfwsaodzyefz
    password: Diucamica23!
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
